RegisterNetEvent('discordhandler:showwatermark', function()
    SetTextScale(2.0, 2.0)
    SetTextOutline()
    SetTextFont(4)
    BeginTextCommandDisplayText("STRING")
    AddTextComponentSubstringPlayerName("please join the discord")
    EndTextCommandDisplayText(0.1, 0.1)
    Wait(10)
end)